name: Metrics

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Run workflow manually
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.skyline.svg
          delay: 5000 # Mantém o delay, mas o foco é reduzir a complexidade

          # Plugins de Skyline
          plugin_skyline: yes
          plugin_skyline_year: current-year
          # !!! REDUZA ESTES VALORES !!!
          plugin_skyline_frames: 30  # Reduzido de 60 para 30
          plugin_skyline_quality: 0.3 # Reduzido de 0.5 para 0.3
