name: Metrics

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Run workflow manually
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.skyline.svg # Nome do arquivo SVG gerado
          # Plugins de Skyline
          plugin_skyline: yes
          plugin_skyline_year: current-year
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.5
          # !!! ADICIONE ESTA LINHA OU AUMENTE O VALOR !!!
          plugin_skyline_timeout: 120000 # Aumentado para 120 segundos (120000ms)
